repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
    exclude: ^docker/.*tests\.yaml$ #fails due to !override, skip for now 
  - id: check-json
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
    files: '^(README.md|docs/)'
    exclude: '^docs/cli/_auto_generated/' # typer generated files everytime mkdocs build/serve is run
  - id: trailing-whitespace
    files: '^(README.md|docs/)'
    exclude: '^docs/cli/_auto_generated/'

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
  - id: markdownlint-fix
    args: ['--config', '.github/.markdownlint.yaml']
    files: '^(README.md|docs)'
    exclude: '^docs/cli/_auto_generated/'

# for python
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
      files: '^(packages|tests)/.*'
    # Run the formatter.
    - id: ruff-format
      files: '^(packages|tests)/.*'

