[tool.uv.workspace]
members = [
    "packages/divbase-cli",
    "packages/divbase-lib",
    "packages/divbase-api",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pre-commit>=3.7.0",
    "pytest-env>=1.1.5",
    "pytest-playwright>=0.7.2",
    "pytest-alembic>=0.12.1",
    "pytest-mock-resources[docker]>=2.12.4",
    "mkdocs>=1.6.1",
    "pymdown-extensions>=10.19.1",
    "mkdocs-material[imaging]>=9.7.0",
]
benchmarking = [
    "scipy>=1.16.0",
    "matplotlib>=3.10",
    "seaborn>=0.13",
    "statsmodels>=0.14.4",
    "requests>=2.32.4",
]