global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'rabbitmq'
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'celery-workers'
    static_configs:
      - targets: ['worker-quick:8101', 'worker-long:8101']