[project]
name = "divbase-cli"
dynamic = ["version"]
description = "Command Line Interface for Divbase"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.15.4",
    "httpx>=0.28.1",
    "divbase-lib",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/divbase_cli/__init__.py"

[tool.uv.sources]
divbase-lib = { workspace = true }

[project.scripts]
divbase = "divbase_cli.divbase_cli:main"
divbase-cli = "divbase_cli.divbase_cli:main"  # TODO choose 1 